# Generated by Django 3.2.1 on 2024-08-24 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='entered_by_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='lga_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='long',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniquewardid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='user_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='ward_id',
            field=models.IntegerField(null=True),
        ),
    ]
