# Generated by Django 3.2.1 on 2024-08-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20240824_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedlgaresults',
            name='date_entered',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='announcedpuresults',
            name='date_entered',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='announcedstateresults',
            name='date_entered',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='announcedwardresults',
            name='date_entered',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lga',
            name='date_entered',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ward',
            name='date_entered',
            field=models.CharField(max_length=100),
        ),
    ]
