# Generated by Django 3.2.1 on 2024-08-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20240824_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
